version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "hello-world-test"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1fzancrdbajo3"
s3_prefix = "hello-world-test"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
