AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM Template for myapp

Globals:
  Function:
    Timeout: 3

Parameters:
  Environment:
    Type: String
    Description: Environment of template
    Default: Dev

Resources:
  ApiGateway:
    Type: 'AWS::Serverless::Api'
    Properties:
      Name: !Sub '${AWS::StackName}'
      StageName: !Sub '${Environment}'
      Auth:
        UsagePlan:
          CreateUsagePlan: PER_API
          UsagePlanName: !Sub '${AWS::StackName}-${Environment}-UsagePlan'
          Quota:
            Limit: 5000
            Period: DAY
          Throttle:
            BurstLimit: 200
            RateLimit: 100
          Description: API Usage Plan
      TracingEnabled: true

  myappFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: deploy
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      FunctionName: myapp
      Environment:
        Variables:
          NODE_ENV: !Ref Environment
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
            RestApiId:
              Ref: ApiGateway
Outputs:
  myappUrl:
    Description: 'API Gateway endpoint URL for function'
    Value: !Sub 'https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/hello'
  myappFunction:
    Description: 'Hello World Lambda Function ARN'
    Value: !GetAtt myappFunction.Arn
  myappFunctionIamRole:
    Description: 'Implicit IAM Role created for Hello World function'
    Value: !GetAtt myappFunctionRole.Arn
