AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM Template for myapp
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Parameters:
  Environment:
    Type: String
    Description: Environment of template
    Default: Dev
    
Resources:
  myappFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: deploy
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Environment:
        Variables:
          NODE_ENV: !Ref Environment
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  myappUrl:
    Description: "API Gateway endpoint URL for function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  myappFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt myappFunction.Arn
  myappFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt myappFunctionRole.Arn
